// Code generated by Fern. DO NOT EDIT.

package client

import (
	analytics "github.com/VapiAI/server-sdk-go/v3/analytics"
	assistants "github.com/VapiAI/server-sdk-go/v3/assistants"
	calls "github.com/VapiAI/server-sdk-go/v3/calls"
	campaigns "github.com/VapiAI/server-sdk-go/v3/campaigns"
	chats "github.com/VapiAI/server-sdk-go/v3/chats"
	core "github.com/VapiAI/server-sdk-go/v3/core"
	eval "github.com/VapiAI/server-sdk-go/v3/eval"
	files "github.com/VapiAI/server-sdk-go/v3/files"
	insight "github.com/VapiAI/server-sdk-go/v3/insight"
	internal "github.com/VapiAI/server-sdk-go/v3/internal"
	observabilityscorecard "github.com/VapiAI/server-sdk-go/v3/observabilityscorecard"
	option "github.com/VapiAI/server-sdk-go/v3/option"
	phonenumbers "github.com/VapiAI/server-sdk-go/v3/phonenumbers"
	providerresources "github.com/VapiAI/server-sdk-go/v3/providerresources"
	sessions "github.com/VapiAI/server-sdk-go/v3/sessions"
	squads "github.com/VapiAI/server-sdk-go/v3/squads"
	structuredoutputs "github.com/VapiAI/server-sdk-go/v3/structuredoutputs"
	tools "github.com/VapiAI/server-sdk-go/v3/tools"
)

type Client struct {
	Assistants             *assistants.Client
	Squads                 *squads.Client
	Calls                  *calls.Client
	Chats                  *chats.Client
	Campaigns              *campaigns.Client
	Sessions               *sessions.Client
	PhoneNumbers           *phonenumbers.Client
	Tools                  *tools.Client
	Files                  *files.Client
	StructuredOutputs      *structuredoutputs.Client
	Insight                *insight.Client
	Eval                   *eval.Client
	ObservabilityScorecard *observabilityscorecard.Client
	ProviderResources      *providerresources.Client
	Analytics              *analytics.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Assistants:             assistants.NewClient(options),
		Squads:                 squads.NewClient(options),
		Calls:                  calls.NewClient(options),
		Chats:                  chats.NewClient(options),
		Campaigns:              campaigns.NewClient(options),
		Sessions:               sessions.NewClient(options),
		PhoneNumbers:           phonenumbers.NewClient(options),
		Tools:                  tools.NewClient(options),
		Files:                  files.NewClient(options),
		StructuredOutputs:      structuredoutputs.NewClient(options),
		Insight:                insight.NewClient(options),
		Eval:                   eval.NewClient(options),
		ObservabilityScorecard: observabilityscorecard.NewClient(options),
		ProviderResources:      providerresources.NewClient(options),
		Analytics:              analytics.NewClient(options),
		options:                options,
		baseURL:                options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
