// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersAnalyticsQueryDto(t *testing.T) {
	t.Run("SetQueries", func(t *testing.T) {
		obj := &AnalyticsQueryDto{}
		var fernTestValueQueries []*AnalyticsQuery
		obj.SetQueries(fernTestValueQueries)
		assert.Equal(t, fernTestValueQueries, obj.Queries)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAnalyticsQueryDto(t *testing.T) {
	t.Run("SetQueries_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryDto{}
		var fernTestValueQueries []*AnalyticsQuery

		// Act
		obj.SetQueries(fernTestValueQueries)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAnalyticsOperation(t *testing.T) {
	t.Run("SetOperation", func(t *testing.T) {
		obj := &AnalyticsOperation{}
		var fernTestValueOperation AnalyticsOperationOperation
		obj.SetOperation(fernTestValueOperation)
		assert.Equal(t, fernTestValueOperation, obj.Operation)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetColumn", func(t *testing.T) {
		obj := &AnalyticsOperation{}
		var fernTestValueColumn AnalyticsOperationColumn
		obj.SetColumn(fernTestValueColumn)
		assert.Equal(t, fernTestValueColumn, obj.Column)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlias", func(t *testing.T) {
		obj := &AnalyticsOperation{}
		var fernTestValueAlias *string
		obj.SetAlias(fernTestValueAlias)
		assert.Equal(t, fernTestValueAlias, obj.Alias)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAnalyticsOperation(t *testing.T) {
	t.Run("GetOperation", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var expected AnalyticsOperationOperation
		obj.Operation = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOperation(), "getter should return the property value")
	})

	t.Run("GetOperation_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsOperation
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOperation() // Should return zero value
	})

	t.Run("GetColumn", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var expected AnalyticsOperationColumn
		obj.Column = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetColumn(), "getter should return the property value")
	})

	t.Run("GetColumn_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsOperation
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetColumn() // Should return zero value
	})

	t.Run("GetAlias", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var expected *string
		obj.Alias = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAlias(), "getter should return the property value")
	})

	t.Run("GetAlias_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		obj.Alias = nil

		// Act & Assert
		assert.Nil(t, obj.GetAlias(), "getter should return nil when property is nil")
	})

	t.Run("GetAlias_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsOperation
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAlias() // Should return zero value
	})

}

func TestSettersMarkExplicitAnalyticsOperation(t *testing.T) {
	t.Run("SetOperation_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var fernTestValueOperation AnalyticsOperationOperation

		// Act
		obj.SetOperation(fernTestValueOperation)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetColumn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var fernTestValueColumn AnalyticsOperationColumn

		// Act
		obj.SetColumn(fernTestValueColumn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlias_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}
		var fernTestValueAlias *string

		// Act
		obj.SetAlias(fernTestValueAlias)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAnalyticsQuery(t *testing.T) {
	t.Run("SetTable", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueTable AnalyticsQueryTable
		obj.SetTable(fernTestValueTable)
		assert.Equal(t, fernTestValueTable, obj.Table)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGroupBy", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueGroupBy []AnalyticsQueryGroupByItem
		obj.SetGroupBy(fernTestValueGroupBy)
		assert.Equal(t, fernTestValueGroupBy, obj.GroupBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGroupByVariableValue", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueGroupByVariableValue []*VariableValueGroupBy
		obj.SetGroupByVariableValue(fernTestValueGroupByVariableValue)
		assert.Equal(t, fernTestValueGroupByVariableValue, obj.GroupByVariableValue)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimeRange", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueTimeRange *TimeRange
		obj.SetTimeRange(fernTestValueTimeRange)
		assert.Equal(t, fernTestValueTimeRange, obj.TimeRange)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOperations", func(t *testing.T) {
		obj := &AnalyticsQuery{}
		var fernTestValueOperations []*AnalyticsOperation
		obj.SetOperations(fernTestValueOperations)
		assert.Equal(t, fernTestValueOperations, obj.Operations)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAnalyticsQuery(t *testing.T) {
	t.Run("GetTable", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected AnalyticsQueryTable
		obj.Table = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTable(), "getter should return the property value")
	})

	t.Run("GetTable_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTable() // Should return zero value
	})

	t.Run("GetGroupBy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected []AnalyticsQueryGroupByItem
		obj.GroupBy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGroupBy(), "getter should return the property value")
	})

	t.Run("GetGroupBy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		obj.GroupBy = nil

		// Act & Assert
		assert.Nil(t, obj.GetGroupBy(), "getter should return nil when property is nil")
	})

	t.Run("GetGroupBy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGroupBy() // Should return zero value
	})

	t.Run("GetGroupByVariableValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected []*VariableValueGroupBy
		obj.GroupByVariableValue = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGroupByVariableValue(), "getter should return the property value")
	})

	t.Run("GetGroupByVariableValue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		obj.GroupByVariableValue = nil

		// Act & Assert
		assert.Nil(t, obj.GetGroupByVariableValue(), "getter should return nil when property is nil")
	})

	t.Run("GetGroupByVariableValue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGroupByVariableValue() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetTimeRange", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected *TimeRange
		obj.TimeRange = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimeRange(), "getter should return the property value")
	})

	t.Run("GetTimeRange_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		obj.TimeRange = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimeRange(), "getter should return nil when property is nil")
	})

	t.Run("GetTimeRange_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimeRange() // Should return zero value
	})

	t.Run("GetOperations", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var expected []*AnalyticsOperation
		obj.Operations = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOperations(), "getter should return the property value")
	})

	t.Run("GetOperations_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		obj.Operations = nil

		// Act & Assert
		assert.Nil(t, obj.GetOperations(), "getter should return nil when property is nil")
	})

	t.Run("GetOperations_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOperations() // Should return zero value
	})

}

func TestSettersMarkExplicitAnalyticsQuery(t *testing.T) {
	t.Run("SetTable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueTable AnalyticsQueryTable

		// Act
		obj.SetTable(fernTestValueTable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGroupBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueGroupBy []AnalyticsQueryGroupByItem

		// Act
		obj.SetGroupBy(fernTestValueGroupBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGroupByVariableValue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueGroupByVariableValue []*VariableValueGroupBy

		// Act
		obj.SetGroupByVariableValue(fernTestValueGroupByVariableValue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimeRange_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueTimeRange *TimeRange

		// Act
		obj.SetTimeRange(fernTestValueTimeRange)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOperations_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}
		var fernTestValueOperations []*AnalyticsOperation

		// Act
		obj.SetOperations(fernTestValueOperations)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAnalyticsQueryResult(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &AnalyticsQueryResult{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimeRange", func(t *testing.T) {
		obj := &AnalyticsQueryResult{}
		var fernTestValueTimeRange *TimeRange
		obj.SetTimeRange(fernTestValueTimeRange)
		assert.Equal(t, fernTestValueTimeRange, obj.TimeRange)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResult", func(t *testing.T) {
		obj := &AnalyticsQueryResult{}
		var fernTestValueResult []map[string]any
		obj.SetResult(fernTestValueResult)
		assert.Equal(t, fernTestValueResult, obj.Result)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAnalyticsQueryResult(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQueryResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetTimeRange", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var expected *TimeRange
		obj.TimeRange = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimeRange(), "getter should return the property value")
	})

	t.Run("GetTimeRange_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		obj.TimeRange = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimeRange(), "getter should return nil when property is nil")
	})

	t.Run("GetTimeRange_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQueryResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimeRange() // Should return zero value
	})

	t.Run("GetResult", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var expected []map[string]any
		obj.Result = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResult(), "getter should return the property value")
	})

	t.Run("GetResult_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		obj.Result = nil

		// Act & Assert
		assert.Nil(t, obj.GetResult(), "getter should return nil when property is nil")
	})

	t.Run("GetResult_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQueryResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResult() // Should return zero value
	})

}

func TestSettersMarkExplicitAnalyticsQueryResult(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimeRange_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var fernTestValueTimeRange *TimeRange

		// Act
		obj.SetTimeRange(fernTestValueTimeRange)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResult_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}
		var fernTestValueResult []map[string]any

		// Act
		obj.SetResult(fernTestValueResult)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTimeRange(t *testing.T) {
	t.Run("SetStep", func(t *testing.T) {
		obj := &TimeRange{}
		var fernTestValueStep *TimeRangeStep
		obj.SetStep(fernTestValueStep)
		assert.Equal(t, fernTestValueStep, obj.Step)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStart", func(t *testing.T) {
		obj := &TimeRange{}
		var fernTestValueStart *time.Time
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnd", func(t *testing.T) {
		obj := &TimeRange{}
		var fernTestValueEnd *time.Time
		obj.SetEnd(fernTestValueEnd)
		assert.Equal(t, fernTestValueEnd, obj.End)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimezone", func(t *testing.T) {
		obj := &TimeRange{}
		var fernTestValueTimezone *string
		obj.SetTimezone(fernTestValueTimezone)
		assert.Equal(t, fernTestValueTimezone, obj.Timezone)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTimeRange(t *testing.T) {
	t.Run("GetStep", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var expected *TimeRangeStep
		obj.Step = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStep(), "getter should return the property value")
	})

	t.Run("GetStep_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		obj.Step = nil

		// Act & Assert
		assert.Nil(t, obj.GetStep(), "getter should return nil when property is nil")
	})

	t.Run("GetStep_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStep() // Should return zero value
	})

	t.Run("GetStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var expected *time.Time
		obj.Start = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStart(), "getter should return the property value")
	})

	t.Run("GetStart_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		obj.Start = nil

		// Act & Assert
		assert.Nil(t, obj.GetStart(), "getter should return nil when property is nil")
	})

	t.Run("GetStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStart() // Should return zero value
	})

	t.Run("GetEnd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var expected *time.Time
		obj.End = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEnd(), "getter should return the property value")
	})

	t.Run("GetEnd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		obj.End = nil

		// Act & Assert
		assert.Nil(t, obj.GetEnd(), "getter should return nil when property is nil")
	})

	t.Run("GetEnd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEnd() // Should return zero value
	})

	t.Run("GetTimezone", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var expected *string
		obj.Timezone = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimezone(), "getter should return the property value")
	})

	t.Run("GetTimezone_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		obj.Timezone = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimezone(), "getter should return nil when property is nil")
	})

	t.Run("GetTimezone_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimezone() // Should return zero value
	})

}

func TestSettersMarkExplicitTimeRange(t *testing.T) {
	t.Run("SetStep_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var fernTestValueStep *TimeRangeStep

		// Act
		obj.SetStep(fernTestValueStep)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var fernTestValueStart *time.Time

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var fernTestValueEnd *time.Time

		// Act
		obj.SetEnd(fernTestValueEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimezone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}
		var fernTestValueTimezone *string

		// Act
		obj.SetTimezone(fernTestValueTimezone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVariableValueGroupBy(t *testing.T) {
	t.Run("SetKey", func(t *testing.T) {
		obj := &VariableValueGroupBy{}
		var fernTestValueKey string
		obj.SetKey(fernTestValueKey)
		assert.Equal(t, fernTestValueKey, obj.Key)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersVariableValueGroupBy(t *testing.T) {
	t.Run("GetKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VariableValueGroupBy{}
		var expected string
		obj.Key = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKey(), "getter should return the property value")
	})

	t.Run("GetKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VariableValueGroupBy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKey() // Should return zero value
	})

}

func TestSettersMarkExplicitVariableValueGroupBy(t *testing.T) {
	t.Run("SetKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VariableValueGroupBy{}
		var fernTestValueKey string

		// Act
		obj.SetKey(fernTestValueKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAnalyticsOperation(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsOperation{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AnalyticsOperation
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsOperation
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsOperation
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingAnalyticsQuery(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQuery{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AnalyticsQuery
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsQuery
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsQuery
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingAnalyticsQueryResult(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalyticsQueryResult{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AnalyticsQueryResult
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsQueryResult
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AnalyticsQueryResult
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTimeRange(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TimeRange{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TimeRange
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TimeRange
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TimeRange
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingVariableValueGroupBy(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VariableValueGroupBy{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled VariableValueGroupBy
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj VariableValueGroupBy
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj VariableValueGroupBy
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAnalyticsOperation(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsOperation{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsOperation
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringAnalyticsQuery(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsQuery{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringAnalyticsQueryResult(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsQueryResult{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQueryResult
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTimeRange(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TimeRange{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringVariableValueGroupBy(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &VariableValueGroupBy{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VariableValueGroupBy
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumAnalyticsOperationColumn(t *testing.T) {
	t.Run("NewFromString_id", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("id")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("id"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_cost", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("cost")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("cost"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_llm", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.llm")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.llm"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_stt", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.stt")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.stt"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_tts", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.tts")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.tts"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_vapi", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.vapi")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.vapi"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_transport", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.transport")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.transport"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_analysisBreakdown_summary", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.analysisBreakdown.summary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.analysisBreakdown.summary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_transcriber", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.transcriber")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.transcriber"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_ttsCharacters", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.ttsCharacters")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.ttsCharacters"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_llmPromptTokens", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.llmPromptTokens")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.llmPromptTokens"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_llmCompletionTokens", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.llmCompletionTokens")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.llmCompletionTokens"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_costBreakdown_llmCachedPromptTokens", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("costBreakdown.llmCachedPromptTokens")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("costBreakdown.llmCachedPromptTokens"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_duration", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("duration")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("duration"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_concurrency", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("concurrency")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("concurrency"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_minutesUsed", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationColumnFromString("minutesUsed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationColumn("minutesUsed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAnalyticsOperationColumnFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAnalyticsOperationColumnFromString("id")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumAnalyticsOperationOperation(t *testing.T) {
	t.Run("NewFromString_sum", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("sum")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("sum"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_avg", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("avg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("avg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_count", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("count")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("count"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_min", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("min")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("min"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_max", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("max")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("max"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_history", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsOperationOperationFromString("history")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsOperationOperation("history"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAnalyticsOperationOperationFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAnalyticsOperationOperationFromString("sum")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumAnalyticsQueryGroupByItem(t *testing.T) {
	t.Run("NewFromString_type", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryGroupByItemFromString("type")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryGroupByItem("type"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_assistantId", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryGroupByItemFromString("assistantId")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryGroupByItem("assistantId"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_endedReason", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryGroupByItemFromString("endedReason")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryGroupByItem("endedReason"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_analysis_successEvaluation", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryGroupByItemFromString("analysis.successEvaluation")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryGroupByItem("analysis.successEvaluation"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_status", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryGroupByItemFromString("status")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryGroupByItem("status"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAnalyticsQueryGroupByItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAnalyticsQueryGroupByItemFromString("type")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumAnalyticsQueryTable(t *testing.T) {
	t.Run("NewFromString_call", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryTableFromString("call")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryTable("call"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_subscription", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalyticsQueryTableFromString("subscription")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalyticsQueryTable("subscription"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAnalyticsQueryTableFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAnalyticsQueryTableFromString("call")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumTimeRangeStep(t *testing.T) {
	t.Run("NewFromString_second", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("second")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("second"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_minute", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("minute")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("minute"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_hour", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("hour")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("hour"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_day", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("day")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("day"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_week", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("week")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("week"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_month", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("month")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("month"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_quarter", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("quarter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("quarter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_year", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("year")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("year"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_decade", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("decade")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("decade"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_century", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("century")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("century"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_millennium", func(t *testing.T) {
		t.Parallel()
		val, err := NewTimeRangeStepFromString("millennium")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TimeRangeStep("millennium"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTimeRangeStepFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTimeRangeStepFromString("second")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesAnalyticsOperation(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsOperation{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsOperation
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesAnalyticsQuery(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsQuery{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQuery
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesAnalyticsQueryResult(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AnalyticsQueryResult{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AnalyticsQueryResult
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTimeRange(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TimeRange{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TimeRange
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesVariableValueGroupBy(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &VariableValueGroupBy{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VariableValueGroupBy
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
