// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersProviderResourceControllerCreateProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResourceControllerCreateProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerCreateProviderResourceRequestProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResourceControllerCreateProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerCreateProviderResourceRequestResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProviderResourceControllerCreateProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerCreateProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerCreateProviderResourceRequestProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerCreateProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerCreateProviderResourceRequestResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResourceControllerDeleteProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerDeleteProviderResourceRequestProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerDeleteProviderResourceRequestResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetId", func(t *testing.T) {
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProviderResourceControllerDeleteProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerDeleteProviderResourceRequestProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerDeleteProviderResourceRequestResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerDeleteProviderResourceRequest{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResourceControllerGetProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerGetProviderResourceRequestProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerGetProviderResourceRequestResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetId", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProviderResourceControllerGetProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerGetProviderResourceRequestProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerGetProviderResourceRequestResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourceRequest{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResourceControllerGetProviderResourcesPaginatedRequest(t *testing.T) {
	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueProvider ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueResourceName ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetId", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueId *string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceId", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueResourceId *string
		obj.SetResourceId(fernTestValueResourceId)
		assert.Equal(t, fernTestValueResourceId, obj.ResourceId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValuePage *float64
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSortOrder", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueSortOrder *ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder
		obj.SetSortOrder(fernTestValueSortOrder)
		assert.Equal(t, fernTestValueSortOrder, obj.SortOrder)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueLimit *float64
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAtGt", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtGt *time.Time
		obj.SetCreatedAtGt(fernTestValueCreatedAtGt)
		assert.Equal(t, fernTestValueCreatedAtGt, obj.CreatedAtGt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAtLt", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtLt *time.Time
		obj.SetCreatedAtLt(fernTestValueCreatedAtLt)
		assert.Equal(t, fernTestValueCreatedAtLt, obj.CreatedAtLt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAtGe", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtGe *time.Time
		obj.SetCreatedAtGe(fernTestValueCreatedAtGe)
		assert.Equal(t, fernTestValueCreatedAtGe, obj.CreatedAtGe)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAtLe", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtLe *time.Time
		obj.SetCreatedAtLe(fernTestValueCreatedAtLe)
		assert.Equal(t, fernTestValueCreatedAtLe, obj.CreatedAtLe)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAtGt", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtGt *time.Time
		obj.SetUpdatedAtGt(fernTestValueUpdatedAtGt)
		assert.Equal(t, fernTestValueUpdatedAtGt, obj.UpdatedAtGt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAtLt", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtLt *time.Time
		obj.SetUpdatedAtLt(fernTestValueUpdatedAtLt)
		assert.Equal(t, fernTestValueUpdatedAtLt, obj.UpdatedAtLt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAtGe", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtGe *time.Time
		obj.SetUpdatedAtGe(fernTestValueUpdatedAtGe)
		assert.Equal(t, fernTestValueUpdatedAtGe, obj.UpdatedAtGe)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAtLe", func(t *testing.T) {
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtLe *time.Time
		obj.SetUpdatedAtLe(fernTestValueUpdatedAtLe)
		assert.Equal(t, fernTestValueUpdatedAtLe, obj.UpdatedAtLe)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProviderResourceControllerGetProviderResourcesPaginatedRequest(t *testing.T) {
	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueProvider ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueResourceName ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueId *string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueResourceId *string

		// Act
		obj.SetResourceId(fernTestValueResourceId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValuePage *float64

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSortOrder_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueSortOrder *ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder

		// Act
		obj.SetSortOrder(fernTestValueSortOrder)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueLimit *float64

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAtGt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtGt *time.Time

		// Act
		obj.SetCreatedAtGt(fernTestValueCreatedAtGt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAtLt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtLt *time.Time

		// Act
		obj.SetCreatedAtLt(fernTestValueCreatedAtLt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAtGe_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtGe *time.Time

		// Act
		obj.SetCreatedAtGe(fernTestValueCreatedAtGe)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAtLe_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueCreatedAtLe *time.Time

		// Act
		obj.SetCreatedAtLe(fernTestValueCreatedAtLe)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAtGt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtGt *time.Time

		// Act
		obj.SetUpdatedAtGt(fernTestValueUpdatedAtGt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAtLt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtLt *time.Time

		// Act
		obj.SetUpdatedAtLt(fernTestValueUpdatedAtLt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAtGe_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtGe *time.Time

		// Act
		obj.SetUpdatedAtGe(fernTestValueUpdatedAtGe)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAtLe_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerGetProviderResourcesPaginatedRequest{}
		var fernTestValueUpdatedAtLe *time.Time

		// Act
		obj.SetUpdatedAtLe(fernTestValueUpdatedAtLe)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResourceControllerUpdateProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerUpdateProviderResourceRequestProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerUpdateProviderResourceRequestResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetId", func(t *testing.T) {
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProviderResourceControllerUpdateProviderResourceRequest(t *testing.T) {
	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueProvider ProviderResourceControllerUpdateProviderResourceRequestProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueResourceName ProviderResourceControllerUpdateProviderResourceRequestResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourceControllerUpdateProviderResourceRequest{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResource(t *testing.T) {
	t.Run("SetId", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueId string
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrgId", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueOrgId string
		obj.SetOrgId(fernTestValueOrgId)
		assert.Equal(t, fernTestValueOrgId, obj.OrgId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueProvider ProviderResourceProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceName", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueResourceName ProviderResourceResourceName
		obj.SetResourceName(fernTestValueResourceName)
		assert.Equal(t, fernTestValueResourceName, obj.ResourceName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceId", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueResourceId string
		obj.SetResourceId(fernTestValueResourceId)
		assert.Equal(t, fernTestValueResourceId, obj.ResourceId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResource", func(t *testing.T) {
		obj := &ProviderResource{}
		var fernTestValueResource map[string]any
		obj.SetResource(fernTestValueResource)
		assert.Equal(t, fernTestValueResource, obj.Resource)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProviderResource(t *testing.T) {
	t.Run("GetId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected string
		obj.Id = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetId(), "getter should return the property value")
	})

	t.Run("GetId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetId() // Should return zero value
	})

	t.Run("GetOrgId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected string
		obj.OrgId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrgId(), "getter should return the property value")
	})

	t.Run("GetOrgId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrgId() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

	t.Run("GetProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected ProviderResourceProvider
		obj.Provider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProvider(), "getter should return the property value")
	})

	t.Run("GetProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProvider() // Should return zero value
	})

	t.Run("GetResourceName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected ProviderResourceResourceName
		obj.ResourceName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResourceName(), "getter should return the property value")
	})

	t.Run("GetResourceName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResourceName() // Should return zero value
	})

	t.Run("GetResourceId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected string
		obj.ResourceId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResourceId(), "getter should return the property value")
	})

	t.Run("GetResourceId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResourceId() // Should return zero value
	})

	t.Run("GetResource", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var expected map[string]any
		obj.Resource = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResource(), "getter should return the property value")
	})

	t.Run("GetResource_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		obj.Resource = nil

		// Act & Assert
		assert.Nil(t, obj.GetResource(), "getter should return nil when property is nil")
	})

	t.Run("GetResource_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResource() // Should return zero value
	})

}

func TestSettersMarkExplicitProviderResource(t *testing.T) {
	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueId string

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrgId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueOrgId string

		// Act
		obj.SetOrgId(fernTestValueOrgId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueProvider ProviderResourceProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueResourceName ProviderResourceResourceName

		// Act
		obj.SetResourceName(fernTestValueResourceName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueResourceId string

		// Act
		obj.SetResourceId(fernTestValueResourceId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}
		var fernTestValueResource map[string]any

		// Act
		obj.SetResource(fernTestValueResource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("SetResults", func(t *testing.T) {
		obj := &ProviderResourcePaginatedResponse{}
		var fernTestValueResults []*ProviderResource
		obj.SetResults(fernTestValueResults)
		assert.Equal(t, fernTestValueResults, obj.Results)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMetadata", func(t *testing.T) {
		obj := &ProviderResourcePaginatedResponse{}
		var fernTestValueMetadata *PaginationMeta
		obj.SetMetadata(fernTestValueMetadata)
		assert.Equal(t, fernTestValueMetadata, obj.Metadata)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("GetResults", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		var expected []*ProviderResource
		obj.Results = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResults(), "getter should return the property value")
	})

	t.Run("GetResults_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		obj.Results = nil

		// Act & Assert
		assert.Nil(t, obj.GetResults(), "getter should return nil when property is nil")
	})

	t.Run("GetResults_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResourcePaginatedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResults() // Should return zero value
	})

	t.Run("GetMetadata", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		var expected *PaginationMeta
		obj.Metadata = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMetadata(), "getter should return the property value")
	})

	t.Run("GetMetadata_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		obj.Metadata = nil

		// Act & Assert
		assert.Nil(t, obj.GetMetadata(), "getter should return nil when property is nil")
	})

	t.Run("GetMetadata_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResourcePaginatedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMetadata() // Should return zero value
	})

}

func TestSettersMarkExplicitProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("SetResults_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		var fernTestValueResults []*ProviderResource

		// Act
		obj.SetResults(fernTestValueResults)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMetadata_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}
		var fernTestValueMetadata *PaginationMeta

		// Act
		obj.SetMetadata(fernTestValueMetadata)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingProviderResource(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResource{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProviderResource
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProviderResource
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProviderResource
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProviderResourcePaginatedResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProviderResourcePaginatedResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProviderResourcePaginatedResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProviderResourcePaginatedResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringProviderResource(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProviderResource{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProviderResourcePaginatedResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResourcePaginatedResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumProviderResourceControllerCreateProviderResourceRequestProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerCreateProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerCreateProviderResourceRequestProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerCreateProviderResourceRequestProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerCreateProviderResourceRequestProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerCreateProviderResourceRequestProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerCreateProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerCreateProviderResourceRequestResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerCreateProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerCreateProviderResourceRequestResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerCreateProviderResourceRequestResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerCreateProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerDeleteProviderResourceRequestProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerDeleteProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerDeleteProviderResourceRequestProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerDeleteProviderResourceRequestProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerDeleteProviderResourceRequestProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerDeleteProviderResourceRequestProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerDeleteProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerDeleteProviderResourceRequestResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerDeleteProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerDeleteProviderResourceRequestResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerDeleteProviderResourceRequestResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerDeleteProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerGetProviderResourceRequestProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourceRequestProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourceRequestProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourceRequestProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerGetProviderResourceRequestProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerGetProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerGetProviderResourceRequestResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourceRequestResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerGetProviderResourceRequestResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerGetProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerGetProviderResourcesPaginatedRequestProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourcesPaginatedRequestProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourcesPaginatedRequestResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder(t *testing.T) {
	t.Run("NewFromString_ASC", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderFromString("ASC")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder("ASC"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_DESC", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderFromString("DESC")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder("DESC"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrderFromString("ASC")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerUpdateProviderResourceRequestProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerUpdateProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerUpdateProviderResourceRequestProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerUpdateProviderResourceRequestProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerUpdateProviderResourceRequestProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerUpdateProviderResourceRequestProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerUpdateProviderResourceRequestProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceControllerUpdateProviderResourceRequestResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceControllerUpdateProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceControllerUpdateProviderResourceRequestResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceControllerUpdateProviderResourceRequestResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceControllerUpdateProviderResourceRequestResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceProvider(t *testing.T) {
	t.Run("NewFromString_cartesia", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceProviderFromString("cartesia")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceProvider("cartesia"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_11labs", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceProviderFromString("11labs")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceProvider("11labs"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceProviderFromString("cartesia")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumProviderResourceResourceName(t *testing.T) {
	t.Run("NewFromString_pronunciation_dictionary", func(t *testing.T) {
		t.Parallel()
		val, err := NewProviderResourceResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProviderResourceResourceName("pronunciation-dictionary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProviderResourceResourceNameFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProviderResourceResourceNameFromString("pronunciation-dictionary")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesProviderResource(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProviderResource{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResource
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProviderResourcePaginatedResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProviderResourcePaginatedResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProviderResourcePaginatedResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
