// Code generated by Fern. DO NOT EDIT.

package structuredoutputs

import (
	context "context"

	serversdkgo "github.com/VapiAI/server-sdk-go/v2"
	core "github.com/VapiAI/server-sdk-go/v2/core"
	internal "github.com/VapiAI/server-sdk-go/v2/internal"
	option "github.com/VapiAI/server-sdk-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns structured-output definitions for the authenticated organization. Filter results by ID, name, or creation and update timestamps.
func (c *Client) StructuredOutputControllerFindAll(
	ctx context.Context,
	request *serversdkgo.StructuredOutputControllerFindAllRequest,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutputPaginatedResponse, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a reusable definition for extracting validated data from conversations using an AI model or regular expression.
func (c *Client) StructuredOutputControllerCreate(
	ctx context.Context,
	request *serversdkgo.CreateStructuredOutputDto,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the structured-output definition identified by its ID.
func (c *Client) StructuredOutputControllerFindOne(
	ctx context.Context,
	request *serversdkgo.StructuredOutputControllerFindOneRequest,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindOne(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes the structured-output definition identified by its ID.
func (c *Client) StructuredOutputControllerRemove(
	ctx context.Context,
	request *serversdkgo.StructuredOutputControllerRemoveRequest,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerRemove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the structured-output definition identified by its ID.
func (c *Client) StructuredOutputControllerUpdate(
	ctx context.Context,
	request *serversdkgo.UpdateStructuredOutputDto,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Runs a saved or transient structured-output definition against one or more calls, optionally returning a preview without updating call artifacts.
func (c *Client) StructuredOutputControllerRun(
	ctx context.Context,
	request *serversdkgo.StructuredOutputRunDto,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerRun(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
