// Code generated by Fern. DO NOT EDIT.

package structuredoutputs

import (
	context "context"
	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) StructuredOutputControllerFindAll(
	ctx context.Context,
	request *serversdkgo.StructuredOutputControllerFindAllRequest,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutputPaginatedResponse, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerCreate(
	ctx context.Context,
	request *serversdkgo.CreateStructuredOutputDto,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerFindOne(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerFindOne(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerRemove(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerRemove(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StructuredOutputControllerUpdate(
	ctx context.Context,
	id string,
	request *serversdkgo.UpdateStructuredOutputDto,
	opts ...option.RequestOption,
) (*serversdkgo.StructuredOutput, error) {
	response, err := c.WithRawResponse.StructuredOutputControllerUpdate(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
