// Code generated by Fern. DO NOT EDIT.

package providerresources

import (
	context "context"
	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ProviderResourceControllerGetProviderResourcesPaginated(
	ctx context.Context,
	// The provider (e.g., 11labs)
	provider string,
	// The resource name (e.g., pronunciation-dictionary)
	resourceName string,
	request *serversdkgo.ProviderResourceControllerGetProviderResourcesPaginatedRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResourcePaginatedResponse, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResourcesPaginated(
		ctx,
		provider,
		resourceName,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerCreateProviderResource(
	ctx context.Context,
	// The provider (e.g., 11labs)
	provider string,
	// The resource name (e.g., pronunciation-dictionary)
	resourceName string,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerCreateProviderResource(
		ctx,
		provider,
		resourceName,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerGetProviderResource(
	ctx context.Context,
	// The provider (e.g., 11labs)
	provider string,
	// The resource name (e.g., pronunciation-dictionary)
	resourceName string,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResource(
		ctx,
		provider,
		resourceName,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerDeleteProviderResource(
	ctx context.Context,
	// The provider (e.g., 11labs)
	provider string,
	// The resource name (e.g., pronunciation-dictionary)
	resourceName string,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerDeleteProviderResource(
		ctx,
		provider,
		resourceName,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ProviderResourceControllerUpdateProviderResource(
	ctx context.Context,
	// The provider (e.g., 11labs)
	provider string,
	// The resource name (e.g., pronunciation-dictionary)
	resourceName string,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerUpdateProviderResource(
		ctx,
		provider,
		resourceName,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
