// Code generated by Fern. DO NOT EDIT.

package providerresources

import (
	context "context"

	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns a paginated list of provider resources for the authenticated organization. Filter pronunciation dictionaries by provider, resource ID, or creation and update timestamps.
func (c *Client) ProviderResourceControllerGetProviderResourcesPaginated(
	ctx context.Context,
	request *serversdkgo.ProviderResourceControllerGetProviderResourcesPaginatedRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResourcePaginatedResponse, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResourcesPaginated(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a pronunciation-dictionary resource for a supported provider, currently Cartesia or ElevenLabs.
func (c *Client) ProviderResourceControllerCreateProviderResource(
	ctx context.Context,
	request *serversdkgo.ProviderResourceControllerCreateProviderResourceRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerCreateProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the provider resource identified by its Vapi resource ID.
func (c *Client) ProviderResourceControllerGetProviderResource(
	ctx context.Context,
	request *serversdkgo.ProviderResourceControllerGetProviderResourceRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerGetProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes the provider resource identified by its Vapi resource ID.
func (c *Client) ProviderResourceControllerDeleteProviderResource(
	ctx context.Context,
	request *serversdkgo.ProviderResourceControllerDeleteProviderResourceRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerDeleteProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the provider resource identified by its Vapi resource ID.
func (c *Client) ProviderResourceControllerUpdateProviderResource(
	ctx context.Context,
	request *serversdkgo.ProviderResourceControllerUpdateProviderResourceRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ProviderResource, error) {
	response, err := c.WithRawResponse.ProviderResourceControllerUpdateProviderResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
