// Code generated by Fern. DO NOT EDIT.

package phonenumbers

import (
	context "context"

	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns phone numbers for the authenticated organization. Filter results by creation or update timestamps and limit the number returned.
func (c *Client) List(
	ctx context.Context,
	request *serversdkgo.ListPhoneNumbersRequest,
	opts ...option.RequestOption,
) ([]*serversdkgo.ListPhoneNumbersResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a Vapi phone number or imports a phone number from a supported provider, including Twilio, Vonage, Telnyx, or a bring-your-own provider.
func (c *Client) Create(
	ctx context.Context,
	request *serversdkgo.CreatePhoneNumbersRequest,
	opts ...option.RequestOption,
) (*serversdkgo.CreatePhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a paginated list of phone numbers for the authenticated organization. Search by name, number, or SIP URI using a partial, case-insensitive match, and filter by creation or update timestamps.
func (c *Client) PhoneNumberControllerFindAllPaginated(
	ctx context.Context,
	request *serversdkgo.PhoneNumberControllerFindAllPaginatedRequest,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumberPaginatedResponse, error) {
	response, err := c.WithRawResponse.PhoneNumberControllerFindAllPaginated(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the phone number resource identified by its ID.
func (c *Client) Get(
	ctx context.Context,
	request *serversdkgo.GetPhoneNumbersRequest,
	opts ...option.RequestOption,
) (*serversdkgo.GetPhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes the phone number resource identified by its ID.
func (c *Client) Delete(
	ctx context.Context,
	request *serversdkgo.DeletePhoneNumbersRequest,
	opts ...option.RequestOption,
) (*serversdkgo.DeletePhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the specified fields of the phone number resource identified by its ID.
func (c *Client) Update(
	ctx context.Context,
	request *serversdkgo.UpdatePhoneNumbersRequest,
	opts ...option.RequestOption,
) (*serversdkgo.UpdatePhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
