// Code generated by Fern. DO NOT EDIT.

package phonenumbers

import (
	context "context"
	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	request *serversdkgo.PhoneNumbersListRequest,
	opts ...option.RequestOption,
) ([]*serversdkgo.PhoneNumbersListResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Create(
	ctx context.Context,
	request *serversdkgo.PhoneNumbersCreateRequest,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumbersCreateResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PhoneNumberControllerFindAllPaginated(
	ctx context.Context,
	request *serversdkgo.PhoneNumberControllerFindAllPaginatedRequest,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumberPaginatedResponse, error) {
	response, err := c.WithRawResponse.PhoneNumberControllerFindAllPaginated(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumbersGetResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumbersDeleteResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Update(
	ctx context.Context,
	id string,
	request *serversdkgo.PhoneNumbersUpdateRequest,
	opts ...option.RequestOption,
) (*serversdkgo.PhoneNumbersUpdateResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
