// Code generated by Fern. DO NOT EDIT.

package files

import (
	context "context"

	serversdkgo "github.com/VapiAI/server-sdk-go/v2"
	core "github.com/VapiAI/server-sdk-go/v2/core"
	internal "github.com/VapiAI/server-sdk-go/v2/internal"
	option "github.com/VapiAI/server-sdk-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns files uploaded to the authenticated organization.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*serversdkgo.File, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Uploads a file for use with a Vapi knowledge base.
func (c *Client) Create(
	ctx context.Context,
	request *serversdkgo.CreateFileDto,
	opts ...option.RequestOption,
) (*serversdkgo.File, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the uploaded file identified by its ID.
func (c *Client) Get(
	ctx context.Context,
	request *serversdkgo.GetFilesRequest,
	opts ...option.RequestOption,
) (*serversdkgo.File, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes the uploaded file identified by its ID.
func (c *Client) Delete(
	ctx context.Context,
	request *serversdkgo.DeleteFilesRequest,
	opts ...option.RequestOption,
) (*serversdkgo.File, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the name of the uploaded file identified by its ID.
func (c *Client) Update(
	ctx context.Context,
	request *serversdkgo.UpdateFileDto,
	opts ...option.RequestOption,
) (*serversdkgo.File, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
