// Code generated by Fern. DO NOT EDIT.

package observabilityscorecard

import (
	context "context"
	serversdkgo "github.com/VapiAI/server-sdk-go"
	core "github.com/VapiAI/server-sdk-go/core"
	internal "github.com/VapiAI/server-sdk-go/internal"
	option "github.com/VapiAI/server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ScorecardControllerGet(
	ctx context.Context,
	request *serversdkgo.ScorecardControllerGetRequest,
	opts ...option.RequestOption,
) (*serversdkgo.Scorecard, error) {
	response, err := c.WithRawResponse.ScorecardControllerGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ScorecardControllerRemove(
	ctx context.Context,
	request *serversdkgo.ScorecardControllerRemoveRequest,
	opts ...option.RequestOption,
) (*serversdkgo.Scorecard, error) {
	response, err := c.WithRawResponse.ScorecardControllerRemove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ScorecardControllerUpdate(
	ctx context.Context,
	request *serversdkgo.UpdateScorecardDto,
	opts ...option.RequestOption,
) (*serversdkgo.Scorecard, error) {
	response, err := c.WithRawResponse.ScorecardControllerUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ScorecardControllerGetPaginated(
	ctx context.Context,
	request *serversdkgo.ScorecardControllerGetPaginatedRequest,
	opts ...option.RequestOption,
) (*serversdkgo.ScorecardPaginatedResponse, error) {
	response, err := c.WithRawResponse.ScorecardControllerGetPaginated(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ScorecardControllerCreate(
	ctx context.Context,
	request *serversdkgo.CreateScorecardDto,
	opts ...option.RequestOption,
) (*serversdkgo.Scorecard, error) {
	response, err := c.WithRawResponse.ScorecardControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
